### ISSUE TITLE
RLBench returning incorrectly shaped gripper_matrix and wrist_camera_matrix?

### ISSUE THREAD

**Issue by ericrosenbrown** [stepjam/RLBench#124]
I pulled the current version of RLBench from master, and now whenever I tried to get an observation from the environment I get the following error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eric/venvs/new_bench/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/eric/venvs/new_bench/lib/python3.7/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/eric/venvs/new_bench/lib/python3.7/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/eric/new_Github/RLBench/rlbench/gym/rlbench_env.py", line 38, in __init__
    _, obs = self.task.reset()
  File "/home/eric/new_Github/RLBench/rlbench/task_environment.py", line 91, in reset
    return desc, self._scene.get_observation()
  File "/home/eric/new_Github/RLBench/rlbench/backend/scene.py", line 261, in get_observation
    if self._obs_config.gripper_matrix else None),
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/eric/venvs/new_bench/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/eric/venvs/new_bench/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 16 into shape (3,4)

I went into the scene.py file, and found that tip.get_matrix().shape was returning a [4,4] matrix, not a [3,4] as the one specified in the file. I changed it (And wrist_camera_matrix) to 4,4 instead and now everything appears to work. Is there something I did incorrectly or is this a bug?

**Comment by stepjam** [comment]
Thanks for pointing out. There was a recent update to PyRep. Will fix shortly.
