### ISSUE TITLE
Handle <Robot_Name> does not exist.

### ISSUE THREAD

**Issue by jtgenova** [stepjam/RLBench#167]
Hi Stephen,

I have added my custom robot, (Wendy), PyRep by following the tutorial. The first picture shown is running the unit test, which shows a warning but at the end, it said okay. I did not do a pull request, not sure if this is needed.

![image](https://user-images.githubusercontent.com/104475121/166404592-52d172b1-904c-4283-ac9e-ff642a9d16fc.png)

Next, I changed the task_builder.py file to use Wendy instead of Panda. The second picture showed the error I'm getting. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/104475121/166404956-f90ad9df-3d49-4270-905a-d324bd42bf21.png)

Thanks!

**Comment by 136676937** [comment]
hello,i have encountered the same problem,do you solve it?

**Comment by Victor-Ultimate** [comment]
Hello, i can not even find the handle panda,. do you solve it?

**Comment by yasibot8** [comment]
Hello, I encounter the same issue.

**Comment by yasibot8** [comment]
> Hi Stephen,
> 
> I have added my custom robot, (Wendy), PyRep by following the tutorial. The first picture shown is running the unit test, which shows a warning but at the end, it said okay. I did not do a pull request, not sure if this is needed.
> 
> ![image](https://user-images.githubusercontent.com/104475121/166404592-52d172b1-904c-4283-ac9e-ff642a9d16fc.png)
> 
> Next, I changed the task_builder.py file to use Wendy instead of Panda. The second picture showed the error I'm getting. Any help would be appreciated.
> 
> ![image](https://user-images.githubusercontent.com/104475121/166404956-f90ad9df-3d49-4270-905a-d324bd42bf21.png)
> 
> Thanks!

I am having this error,
python dataset_generator.py --tasks=take_lid_off_saucepan --renderer=opengl --episodes_per_task=100 --variations=1 --processes=1
tasks [<class 'rlbench.tasks.take_lid_off_saucepan.TakeLidOffSaucepan'>]
QCoreApplication::applicationFilePath: Please instantiate the QApplication object first
[CoppeliaSim:loadinfo] Application directory is /home/yasir/.local/bin/CoppeliaSim
WARNING: QApplication was not created in the main() thread.
.
.
.
Traceback (most recent call last):
File "/home/yasir/anaconda3/envs/arm/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/home/yasir/anaconda3/envs/arm/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "dataset_generator.py", line 199, in run
rlbench_env.launch()
File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/rlbench/environment.py", line 122, in launch
arm, gripper = arm_class(), gripper_class()
File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/robots/arms/panda.py", line 12, in init
super().init(
File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/robots/arms/arm.py", line 25, in init
super().init(count, name, joint_names, base_name)
File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/robots/robot_component.py", line 19, in init
super().init(
File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/objects/object.py", line 25, in init
self._handle = sim.simGetObjectHandle(name_or_handle)
File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/backend/sim.py", line 94, in simGetObjectHandle
raise RuntimeError('Handle %s does not exist.' % objectName)
RuntimeError: Handle Panda does not exist.
