### ISSUE TITLE
Error with dataset_generator

### ISSUE THREAD

**Issue by diegomaureira** [stepjam/RLBench#175]
Hello, I'm trying to get demos of the eight tasks used for testing the ARM Algorithm ([https://arxiv.org/abs/2105.14829](https://arxiv.org/abs/2105.14829)) but with a different arm, in this case I changed the 'robot_setup' in the environment from panda to jaco:

rlbench_env = Environment(
        action_mode=MoveArmThenGripper(JointVelocity(), Discrete()),
        robot_setup='jaco',
        obs_config=obs_config,
        headless=True)
    rlbench_env.launch()

 I started with take lid off saucepan task, but I have this error. 
 
python3 dataset_generator.py --save_path=/home/diego/demosRL --tasks=take_lid_off_saucepan --image_size=128,128 --renderer=opengl --episodes_per_task=10 --variations=1 --processes=1

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Process Process-2:
Traceback (most recent call last):
  File "/home/diego/anaconda3/lib/python3.9/site-packages/rlbench/task_environment.py", line 78, in reset
    desc = self._scene.init_episode(
  File "/home/diego/anaconda3/lib/python3.9/site-packages/rlbench/backend/scene.py", line 141, in init_episode
    raise e
  File "/home/diego/anaconda3/lib/python3.9/site-packages/rlbench/backend/scene.py", line 133, in init_episode
    raise BoundaryError()
rlbench.backend.exceptions.BoundaryError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/diego/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/diego/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/diego/Documentos/RLBench/tools/dataset_generator.py", line 248, in run
    obs, descriptions = task_env.reset()
  File "/home/diego/anaconda3/lib/python3.9/site-packages/rlbench/task_environment.py", line 82, in reset
    raise TaskEnvironmentError(
rlbench.backend.exceptions.TaskEnvironmentError: Could not place the task take_lid_off_saucepan in the scene. This should not happen, please raise an issues on this task.
Data collection done!

I have the same error with the other 7 tasks. I tried with sawyer, panda and ur5 and those arms work fine, but jaco and mico don't work. Anyone has an idea about what is happening here? thanks in advance.

**Comment by yasibot8** [comment]
I am having this error, 
python dataset_generator.py  --tasks=take_lid_off_saucepan  --renderer=opengl --episodes_per_task=100 --variations=1 --processes=1
tasks [<class 'rlbench.tasks.take_lid_off_saucepan.TakeLidOffSaucepan'>]
QCoreApplication::applicationFilePath: Please instantiate the QApplication object first
[CoppeliaSim:loadinfo]   Application directory is /home/yasir/.local/bin/CoppeliaSim
WARNING: QApplication was not created in the main() thread.
.
.
.
Traceback (most recent call last):
  File "/home/yasir/anaconda3/envs/arm/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/yasir/anaconda3/envs/arm/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "dataset_generator.py", line 199, in run
    rlbench_env.launch()
  File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/rlbench/environment.py", line 122, in launch
    arm, gripper = arm_class(), gripper_class()
  File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/robots/arms/panda.py", line 12, in __init__
    super().__init__(
  File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/robots/arms/arm.py", line 25, in __init__
    super().__init__(count, name, joint_names, base_name)
  File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/robots/robot_component.py", line 19, in __init__
    super().__init__(
  File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/objects/object.py", line 25, in __init__
    self._handle = sim.simGetObjectHandle(name_or_handle)
  File "/home/yasir/anaconda3/envs/arm/lib/python3.8/site-packages/pyrep/backend/sim.py", line 94, in simGetObjectHandle
    raise RuntimeError('Handle %s does not exist.' % objectName)
RuntimeError: Handle Panda does not exist.

**Comment by JYMiracle305** [comment]
I also encountered the same error

**Comment by zst1406217** [comment]
Same error of that
