### ISSUE TITLE
cannot reshape array of size 16 into shape (3,4)

### ISSUE THREAD

**Issue by zhuchengyao** [stepjam/RLBench#222]
I setup the environment and run a sample. But get into the error below.

(VoxPoser) cyzhu@Fudan-ai:~/VoxPoser/RLBench/examples$ python3 single_task_rl.py 
Reset Episode
Traceback (most recent call last):
  File "/nfs/cyzhu/VoxPoser/RLBench/examples/single_task_rl.py", line 37, in <module>
    descriptions, obs = task.reset()
                        ^^^^^^^^^^^^
  File "/nfs/cyzhu/VoxPoser/RLBench/rlbench/task_environment.py", line 91, in reset
    return desc, self._scene.get_observation()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/cyzhu/VoxPoser/RLBench/rlbench/backend/scene.py", line 258, in get_observation
    np.reshape(tip.get_matrix(), (3, 4))
  File "/nfs/cyzhu/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 285, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/cyzhu/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 16 into shape (3,4)
QObject::~QObject: Timers cannot be stopped from another thread
QMutex: destroying locked mutex

**Comment by JYMiracle305** [comment]
Have you solved the error. I meet the same. Thanks for your reply
