### ISSUE TITLE
No module named 'rlbench.action_modes'; 'rlbench' is not a package

### ISSUE THREAD

**Issue by rongkunxue** [stepjam/RLBench#246]
When I followed the tutorial and ran the example, I encountered this issue:
Traceback (most recent call last):
  File "/root/exp/rlbench.py", line 2, in <module>
    from rlbench.action_modes.action_mode import MoveArmThenGripper
  File "/root/exp/rlbench.py", line 2, in <module>
    from rlbench.action_modes.action_mode import MoveArmThenGripper
ModuleNotFoundError: No module named 'rlbench.action_modes'; 'rlbench' is not a package
What should I do?

**Comment by rongkunxue** [comment]
<img width="898" alt="image" src="https://github.com/user-attachments/assets/bae35a54-6d56-4cdb-81cd-04c6ebec289c">

**Comment by Lr-2002** [comment]
i'm facing the same problem, Have you ever solved it ?

**Comment by Lr-2002** [comment]
ohoh, the problem solved, you need to use the system variable as mentioned on the doc
