### ISSUE TITLE
EmptyContainer task crashes with FileNotFoundError

### ISSUE THREAD

**Issue by adamconkey** [stepjam/RLBench#29]
When I run the EmptyContainer task, I get the error:
```
Traceback (most recent call last):
  File "collect_rlbench_data.py", line 192, in <module>
    collect_demos(env, tasks, h5_root, args.n_demos_per_task, len(tasks))
  File "collect_rlbench_data.py", line 103, in collect_demos
    demo = task.get_demos(1, live_demos=True)[0]
  File "/home/adam/venv3/lib/python3.5/site-packages/rlbench/task_environment.py", line 239, in get_demos
    demos = self._get_live_demos(amount)
  File "/home/adam/venv3/lib/python3.5/site-packages/rlbench/task_environment.py", line 248, in _get_live_demos
    self.reset()
  File "/home/adam/venv3/lib/python3.5/site-packages/rlbench/task_environment.py", line 71, in reset
    randomly_place=not self._static_positions)
  File "/home/adam/venv3/lib/python3.5/site-packages/rlbench/backend/scene.py", line 93, in init_episode
    descriptions = self._active_task.init_episode(index)
  File "/home/adam/venv3/lib/python3.5/site-packages/rlbench/tasks/empty_container.py", line 36, in init_episode
    self.bin_objects = sample_procedural_objects(self.get_base(), 3)
  File "/home/adam/venv3/lib/python3.5/site-packages/rlbench/backend/task_utils.py", line 10, in sample_procedural_objects
    os.listdir(assets_dir), num_samples, replace=False)
FileNotFoundError: [Errno 2] No such file or directory: '/home/adam/venv3/lib/python3.5/site-packages/rlbench/backend/../assets/procedural_objects'
QObject::~QObject: Timers cannot be stopped from another thread
QMutex: destroying locked mutex
```

**Comment by stepjam** [comment]
Hi Adam,
This is strange as the CI server doesn't catch this. I'm wondering if it's perhaps something to do with the  virtual env :thinking:. In the setup.py script, the assets directory is included for install. Could you perhaps try running that task outside a venv and see if you still get an issue?

**Comment by stepjam** [comment]
I was able to reproduce this. Fix on the way.
