### ISSUE TITLE
dataset generator not working for new task

### ISSUE THREAD

**Issue by kamaleshrathinam** [stepjam/RLBench#62]
I have created a new task and after variation validator, I tried to get the demos of that task. But running the dataset said that it couldn't find my task.

cmd:python3 tools/dataset_generator.py --tasks left_target --episodes_per_task 2
out:Traceback (most recent call last):
  File "tools/dataset_generator.py", line 295, in <module>
    app.run(main)
  File "/home/vicky/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vicky/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tools/dataset_generator.py", line 265, in main
    raise ValueError('Task %s not recognised!.' % t)
ValueError: Task left_target not recognised!.

**Comment by kamaleshrathinam** [comment]
Was Python Interpreter Issue.
